---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster17.yaml
  - ./outline.yaml
  #  - ./plane.yaml
  - ./prometheusrule.yaml
  - ./scheduledbackup.yaml
  - ./objectstore-postgres17-barman.yaml
