---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-s3-postgres17
spec:
  configuration:
    data:
      compression: bzip2
    destinationPath: s3://cloudnative-pg/
    endpointURL: https://s3.pipitonelabs.com
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: minio-aws-access-key-id
      secretAccessKey:
        name: cloudnative-pg-secret
        key: minio-aws-secret-access-key
    wal:
      compression: bzip2
      maxParallel: 4
  retentionPolicy: 30d