---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
#apiVersion: postgresql.cnpg.io/v1
#kind: ScheduledBackup
#metadata:
#  name: postgres17
#spec:
#  schedule: "@daily"
#  immediate: true
#  backupOwnerReference: self
#  cluster:
#    name: postgres17
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: postgres17-onetime-20250402-1810
spec:
  cluster:
    name: postgres17
  method: barmanObjectStore