---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name "${APP}-initdb"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-initdb-secret"
    template:
      data:
        INIT_POSTGRES_DBNAME: ${APP}
        INIT_POSTGRES_HOST: ${CNPG_NAME:=postgres17}-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .${APP}_POSTGRES_USERNAME }}"
        INIT_POSTGRES_PASS: "{{ .${APP}_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${APP}-pguser"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-pguser-secret"
    template:
      data:
        port: "5432"
        host: ${CNPG_NAME:=postgres17}-rw.database.svc.cluster.local
        user: "{{ .${APP}_POSTGRES_USERNAME }}"
        password: "{{ .${APP}_POSTGRES_PASSWORD }}"
        db: "${APP}"
        uri: postgresql://${APP}:{{ .${APP}_POSTGRES_PASSWORD }}@${CNPG_NAME:=postgres17}-rw.database.svc.cluster.local:5432/${APP}
  dataFrom:
    - extract:
        key: cloudnative-pg
