---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: app-connector
spec:
  appConnector:
    routes:
      - 10.0.0.0/8
      - 192.168.10.0/24
      - 192.168.20.0/24
  hostname: tslamars-ingress