---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: media-smb-unaspro
spec:
  capacity:
    storage: 60Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3.1.1
    - noperm
    - uid=1001
    - forceuid
    - gid=988
    - forcegid
    - iocharset=utf8
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: unaspro/media##
    volumeAttributes:
      source: "//unaspro.internal/media"
    nodeStageSecretRef:
      name: media-smb-unaspro
      namespace: media
