---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-smb-unaspro
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Ti
  volumeName: default-media-smb-unaspro
  storageClassName: ""
