---
originRequest:
  originServerName: external.tslamars.com

ingress:
  - hostname: tslamars.com
    service: &service https://envoy-gateway-external.networking.svc.cluster.local
  - hostname: "*.tslamars.com"
    service: *service
  - service: http_status:404
