---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notifiarr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: notifiarr-secret
    template:
      data:
        DN_API_KEY: "{{ .NOTIFIARR_DN_API_KEY }}"
        DN_UI_PASSWORD: "{{ .NOTIFIARR_DN_UI_PASSWORD }}"
        DN_RADARR_0_API_KEY: "{{ .RADARR_API_KEY }}"
        DN_SONARR_0_API_KEY: "{{ .SONARR_API_KEY }}"
        DN_TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"
        DN_PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
  dataFrom:
    - extract:
        key: notifiarr
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: plex
    - extract:
        key: tautulli
