USER-SUPPLIED VALUES:
cephBlockPools:
- name: ceph-blockpool
  spec:
    failureDomain: host
    replicated:
      size: 3
  storageClass:
    allowVolumeExpansion: true
    enabled: true
    isDefault: true
    name: ceph-block
    parameters:
      csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
      csi.storage.k8s.io/controller-expand-secret-namespace: '{{ .Release.Namespace
        }}'
      csi.storage.k8s.io/fstype: ext4
      csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
      csi.storage.k8s.io/node-stage-secret-namespace: '{{ .Release.Namespace }}'
      csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
      csi.storage.k8s.io/provisioner-secret-namespace: '{{ .Release.Namespace }}'
      imageFeatures: layering,exclusive-lock,object-map,fast-diff,deep-flatten
      imageFormat: "2"
    reclaimPolicy: Delete
cephBlockPoolsVolumeSnapshotClass:
  deletionPolicy: Delete
  enabled: true
  isDefault: true
  name: csi-ceph-block
cephClusterSpec:
  crashCollector:
    disable: false
  csi:
    readAffinity:
      enabled: true
  dashboard:
    enabled: true
    prometheusEndpoint: http://prometheus-operated.monitoring.svc.cluster.local:9090
    ssl: false
    urlPrefix: /
  mgr:
    modules:
    - enabled: true
      name: pg_autoscaler
  network:
    addressRanges:
      cluster:
      - 169.254.255.0/24
      public:
      - 192.168.10.0/24
    connections:
      requireMsgr2: true
    provider: host
  storage:
    deviceFilter: nvme1n1
    useAllDevices: false
    useAllNodes: true
cephFileSystems: []
cephObjectStores: []
monitoring:
  createPrometheusRules: true
  enabled: true
toolbox:
  enabled: true
