---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tslamars-com
spec:
  secretName: tslamars-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: tslamars.com
  dnsNames: ["tslamars.com", "*.tslamars.com"]
