---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${APP}-smb-repo
spec:
  accessModes:
    - ReadWriteMany # SMB supports multiple readers/writers
  capacity:
    storage: 10Gi # Adjust as needed
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: ${APP}-smb-repo-volsync-unaspro # Unique ID
    volumeAttributes:
      source: "//unaspro.internal/Volsync"
    nodeStageSecretRef:
      name: ${APP}-volsync-secret # Uses SMB_USERNAME, SMB_PASSWORD
      namespace: volsync-system
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}-smb-repo
  namespace: volsync-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "" # Bind to specific PV
  volumeName: ${APP}-smb-repo