---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${APP}-smb-repo
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: ${APP}-smb-repo-volsync-unaspro
    volumeAttributes:
      source: "//unaspro.internal/Volsync"
    nodeStageSecretRef:
      name: ${APP}-volsync-secret
      namespace: volsync-system
    mountOptions:
      - dir_mode=0777
      - file_mode=0777
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}-smb-repo
  namespace: volsync-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: ${APP}-smb-repo