apiVersion: v1
kind: ConfigMap
metadata:
  name: kubero-config
data:
  config.yaml: |
    contexts:
      - name: default
        cluster:
          name: default
          server: https://kubero.default.svc.cluster.local
          tls: true
          ca: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          token: /var/run/secrets/kubernetes.io/serviceaccount/token
        namespace: default
        buildpacks:
          - name: heroku/buildpacks:20
        registries:
          - name: dockerhub
            url: https://index.docker.io/v1/
            username: ""
            password: ""