---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kubero
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kubero-secret
    creationPolicy: Owner
    template:
      data:
        KUBERO_WEBHOOK_SECRET: "{{ .KUBERO_WEBHOOK_SECRET }}"
        KUBERO_SESSION_KEY: "{{ .KUBERO_SESSION_KEY }}"
        KUBERO_ADMIN_USERNAME: "{{ .KUBERO_ADMIN_USERNAME }}"
        KUBERO_ADMIN_PASSWORD: "{{ .KUBERO_ADMIN_PASSWORD }}"
        GITHUB_TOKEN: "{{ .KUBERO_GITHUB_TOKEN }}"
  dataFrom:
    - extract:
        key: kubero