apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app kubero
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kubero-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        KUBERO_SESSION_SECRET: "{{ .KUBERO_SESSION_SECRET }}"
        KUBERO_WEBHOOK_SECRET: "{{ .KUBERO_WEBHOOK_SECRET }}"
  dataFrom:
    - extract:
        key: *app