---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kubero
  namespace: &namespace default
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      kubero:
        annotations:
          reloader.stakater.com/auto: "true"
        serviceAccount:
          name: kubero
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          01-init-data:
            image:
              repository: ghcr.io/home-operations/busybox
              tag: 1.37.0@sha256:026ed7273270ec08f6902b4ae8334c23b473e5394bec3bbbdbfe580c710d50bc
            command:
              - sh
              - -c
              - |
                mkdir -p /data
                touch /data/database.db
                chmod 755 /data
                chmod 644 /data/database.db
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
        containers:
          main:
            image:
              repository: ghcr.io/kubero-dev/kubero/kubero
              tag: v3.1.1
            env:
              DATABASE_URL: file:/data/database.db
              PROMETHEUS_URL: http://prometheus-operated.observability.svc.cluster.local:9090
              KUBERO_NAMESPACE: default
              KUBERO_CONTEXT: ""
              KUBERO_WEBHOOK_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: kubero-secret
                    key: KUBERO_WEBHOOK_SECRET
              KUBERO_SESSION_KEY:
                valueFrom:
                  secretKeyRef:
                    name: kubero-secret
                    key: KUBERO_SESSION_KEY
              KUBERO_ADMIN_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: kubero-secret
                    key: KUBERO_ADMIN_USERNAME
              KUBERO_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: kubero-secret
                    key: KUBERO_ADMIN_PASSWORD
              GITHUB_PERSONAL_ACCESS_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: kubero-secret
                    key: GITHUB_PERSONAL_ACCESS_TOKEN
              KUBERO_WEBHOOK_URL:
                valueFrom:
                  secretKeyRef:
                    name: kubero-secret
                    key: KUBERO_WEBHOOK_URL
              KUBERO_CONSOLE_ENABLED: "true"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 2000
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
            resources:
              requests:
                memory: 128Mi
                cpu: 100m
              limits:
                memory: 1Gi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 2000
    route:
      app:
        hostnames: ["kubero.pipitonelabs.com"]
        parentRefs:
          - name: envoy-external
            namespace: networking
    persistence:
      data:
        existingClaim: kubero
        advancedMounts:
          kubero:
            01-init-data:
              - path: /data
            main:
              - path: /data
      config:
        enabled: true
        type: configMap
        name: kubero-config
        globalMounts:
          - path: /app/server/config/kubero.yaml
            subPath: kubero
