---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: homelab
spec:
  module: icmp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        #- unifi.internal
        - mars.internal
        #- ups.internal
        #- kvm.internal
        #- pikvm.internal
        #- zigbee-controller.internal
        #- lutron-bridge.internal
        #- wan1.internal # WAN1 - XFINITY PON ONT
        #- wan2.internal # WAN2 - VZW 4G/5G
