---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: amazon-ses
spec:
  endpoints:
    - dnsName: okishhkqerb7qdn4yg7lbrsoogj4eg5f._domainkey.tslamars.com
      recordType: CNAME
      targets:
        - okishhkqerb7qdn4yg7lbrsoogj4eg5f.dkim.amazonses.com
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
    - dnsName: kwp3ule4u24oudnomeywzovimfpnjww5._domainkey.tslamars.com
      recordType: CNAME
      targets:
        - kwp3ule4u24oudnomeywzovimfpnjww5.dkim.amazonses.com
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
    - dnsName: wcmfwyq325ay55xtahq3yjojbnyzyfja._domainkey.tslamars.com
      recordType: CNAME
      targets:
        - wcmfwyq325ay55xtahq3yjojbnyzyfja.dkim.amazonses.com
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
    - dnsName: mail
      recordType: MX
      targets:
        - feedback-smtp.us-east-1.amazonses.com
    - dnsName: mail
      recordType: TXT
      targets:
        - v=spf1 include:amazonses.com ~all
    - dnsName: _dmarc.tslamars.com
      recordType: TXT
      targets:
        - v=DMARC1; p=none;
