---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/namespace
resources:
#  - ./emqx/ks.yaml
#  - ./garage/ks.yaml
  - ./n8n/ks.yaml
  - ./outline/ks.yaml
  - ./smtp-relay/ks.yaml
#  - ./teslamate/ks.yaml
  - ./nginx/ks.yaml
#  - ./wiki/ks.yaml