---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${APP}-crunchy-postgres"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .MINIO_ACCESS_KEY_ID }}
          repo1-s3-key-secret={{ .MINIO_SECRET_ACCESS_KEY }}
        encryption.conf: |
          [global]
          repo1-cipher-pass={{ .CRUNCHY_PGO_CIPHER_PASS }}
  dataFrom:
    - extract:
        key: crunchy-pgo
    - extract:
        key: minio
