---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
components:
  - ../../components/namespace
resources:
  - ./cloudflare-tunnel/ks.yaml
  - ./cloudflare-dns/ks.yaml
#  - ./echo-server/ks.yaml
  - ./envoy-gateway/ks.yaml
#  - ./multus/ks.yaml
#  - ./tailscale-operator/ks.yaml
  - ./unifi-dns/ks.yaml