---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smb-media-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: smb-media-credentials
    template:
      data:
        smbuser: "{{ .SMB_MEDIA_USERNAME }}"
        smbpassword: "{{ .SMB_MEDIA_PASSWORD }}"
  dataFrom:
    - extract:
        key: smb-media-credentials
