---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app plane
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plane-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Plane
        SECRET_KEY: "{{ .PLANE_SECRET_KEY }}"
        REDIS_PASSWORD: "{{ .PLANE_REDIS_PASSWORD | default \"\" }}"
  dataFrom:
    - extract:
        key: plane