---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plane-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Plane App Secrets
        SECRET_KEY: "{{ .PLANE_SECRET_KEY }}"
        REDIS_PASSWORD: "{{ .PLANE_REDIS_PASSWORD | default \"\" }}"
        # Postgres Secrets
        PGDB_PASSWORD: "{{ .PLANE_PGDB_PASSWORD | default 'plane' }}"
  dataFrom:
    - extract:
        key: plane
  # Refresh interval for secrets
  refreshInterval: 1h
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-pguser-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: plane-pguser-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        uri: "postgresql://plane:{{ .PLANE_PGDB_PASSWORD | default 'plane' }}@plane-postgres.default.svc.cluster.local:5432/plane"
  dataFrom:
    - extract:
        key: plane
  refreshInterval: 1h