---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: makeplane
  namespace: flux-system
spec:
  interval: 30m
  url: https://makeplane.github.io/helm-charts/
  timeout: 5m