---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plane
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: HelmRepository
    name: makeplane
    namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      tag: latest
    database:
      host: plane-rw.database.svc.cluster.local
      port: 5432
      name: plane
      user: plane
      password: ""  # Set via extraEnv
    redis:
      host: plane-dragonfly.default.svc.cluster.local
      port: 6379
      password: ""
    secretKey: ""  # Set via extraEnv
    web:
      host: plane.tslamars.com
      extraEnv:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: plane-pguser-secret
              key: password
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: plane-secret
              key: SECRET_KEY
    api:
      extraEnv:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: plane-pguser-secret
              key: password
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: plane-secret
              key: SECRET_KEY
    worker:
      extraEnv:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: plane-pguser-secret
              key: password
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: plane-secret
              key: SECRET_KEY
    migrator:
      extraEnv:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: plane-pguser-secret
              key: password
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: plane-secret
              key: SECRET_KEY