---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plane
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      plane-backend:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: "17"
            envFrom:
              - secretRef:
                  name: plane-initdb-secret
          02-migrate:
            image:
              repository: makeplane/plane-backend
              tag: latest
            command: ["takeoff"]
            args: ["migrate"]
            env:
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: &pguser plane-app
                    key: uri
              REDIS_URL: redis://plane-dragonfly.default.svc.cluster.local:6379
              SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: plane-secret
                    key: SECRET_KEY
              DJANGO_SETTINGS_MODULE: plane.settings.production
              WEB_BASE_URL: https://plane.tslamars.com
              ENABLE_OAUTH: "0"
            envFrom:
              - secretRef:
                  name: plane-secret
        containers:
          app:
            image:
              repository: makeplane/plane-backend
              tag: latest
            command: ["takeoff"]
            args: ["api"]
            env:
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: *pguser
                    key: uri
              REDIS_URL: redis://plane-dragonfly.default.svc.cluster.local:6379
              SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: plane-secret
                    key: SECRET_KEY
              DJANGO_SETTINGS_MODULE: plane.settings.production
              WEB_BASE_URL: https://plane.tslamars.com
              ENABLE_OAUTH: "0"
              ALLOWED_HOSTS: plane.tslamars.com
              CORS_ALLOWED_ORIGINS: https://plane.tslamars.com
            envFrom:
              - secretRef:
                  name: plane-secret
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                cpu: 500m
                memory: 2Gi
      plane-frontend:
        containers:
          app:
            image:
              repository: makeplane/plane-frontend
              tag: latest
            command: ["npm", "run", "start"]
            workingDir: /app
            env:
              NEXT_PUBLIC_API_BASE_URL: https://plane.tslamars.com/api
              NEXT_PUBLIC_WEB_BASE_URL: https://plane.tslamars.com
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 100m
                memory: 512Mi
      plane-worker:
        containers:
          app:
            image:
              repository: makeplane/plane-worker
              tag: latest
            command: ["./bin/takeoff"]
            args: ["worker"]
            env:
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: *pguser
                    key: uri
              REDIS_URL: redis://plane-dragonfly.default.svc.cluster.local:6379
              SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: plane-secret
                    key: SECRET_KEY
              DJANGO_SETTINGS_MODULE: plane.settings.production
              WEB_BASE_URL: https://plane.tslamars.com
              ENABLE_OAUTH: "0"
            envFrom:
              - secretRef:
                  name: plane-secret
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 200m
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    service:
      backend:
        controller: plane-backend
        ports:
          http:
            port: 8000
      frontend:
        controller: plane-frontend
        ports:
          http:
            port: 3000
    route:
      app:
        hostnames:
          - "plane.tslamars.com"
        parentRefs:
          - name: envoy-external
            namespace: networking
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /api
            backendRefs:
              - identifier: backend
                port: 8000
          - backendRefs:
              - identifier: frontend
                port: 3000
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp