---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ## Non Cluster resources
        HOMEPAGE_VAR_CLOUDFLARE_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
        HOMEPAGE_VAR_CLOUDFLARE_TUNNELID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN: "{{ .CLOUDFLARE_HOMEPAGE_TOKEN }}"
        ## Downloads
        #HOMEPAGE_VAR_BAZARR_API_KEY: "{{ .BAZARR_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_SABNZBD_API_KEY: "{{ .SABNZBD_API_KEY }}"
        HOMEPAGE_VAR_SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        #HOMEPAGE_VAR_AUTOBRR_API_KEY: "{{ .AUTOBRR_API_KEY }}"
        HOMEPAGE_VAR_JELLYSEERR_API_KEY: "{{ .JELLYSEERR_API_KEY }}"
        HOMEPAGE_VAR_PLEX_API_KEY: "{{ .PLEX_API_TOKEN }}"
        HOMEPAGE_VAR_TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"
        HOMEPAGE_VAR_IMMICH_API_KEY: "{{ .IMMICH_API_KEY }}"
        #HOMEPAGE_VAR_PAPERLESS_API_TOKEN: "{{ .PAPERLESS_API_TOKEN }}"
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .UNIFI_HOMEPAGE_USER }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .UNIFI_HOMEPAGE_PASSWORD }}"
        HOMEPAGE_VAR_UNIFI_API_KEY: "{{ .UNIFI_API_KEY }}"
        #HOMEPAGE_VAR_UNIFI_USER: "{{ .UNIFI_POLLER_USER }}"
        #HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .UNIFI_POLLER_PASSWORD }}"
  dataFrom:
    #- extract:
    #    key: autobrr
    #- extract:
    #    key: bazarr
    - extract:
        key: cloudflare
    - extract:
        key: immich
    - extract:
        key: jellyseerr
    - extract:
        key: plex
    - extract:
        key: prowlarr
    - extract:
        key: radarr
    - extract:
        key: sabnzbd
    - extract:
        key: sonarr
    - extract:
        key: tautulli
    - extract:
        key: unraid
    - extract:
        key: unifi
