---
ingress:
  - hostname: "*.pipitonelabs.com"
    service: https://envoy-external.networking.svc.cluster.local
    originRequest:
      http2Origin: true
      originServerName: external.pipitonelabs.com
  - service: http_status:404