---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: volsync-smb-unaspro
  namespace: volsync-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: volsync-smb-unaspro
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
    - extract:
        key: smb-unaspro-volsync
