---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name headlamp-secret
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        # OIDC variables for Headlamp
        HEADLAMP_CONFIG_OIDC_IDP_ISSUER_URL: "https://sso.tslamars.com/application/o/headlamp/"
        HEADLAMP_CONFIG_OIDC_CLIENT_ID: "{{ .HEADLAMP_CLIENT_ID }}"
        HEADLAMP_CONFIG_OIDC_CLIENT_SECRET: "{{ .HEADLAMP_CLIENT_SECRET }}"
        HEADLAMP_CONFIG_OIDC_SCOPES: "openid email profile"
  dataFrom:
  - extract:
      key: headlamp